Trigger ide.kaitai.io/devel rebuild after NPM publish
kaitai-io/kaitai_struct pull request #1124
Opened 2024-08-15 20:47 UTC by jtbandes

Triggers the kaitai_struct_webide workflow to re-run (see https://github.com/kaitai-io/kaitai_struct_webide/pull/181) after the NPM publish step.

This will require adding a [repository secret](https://docs.github.com/en/actions/security-for-github-actions/security-guides/using-secrets-in-github-actions#creating-secrets-for-a-repository) to the `kaitai_struct` repo named `KAITAI_STRUCT_WEBIDE_GITHUB_TOKEN`, which should hold a github access token with `contents: write` permissions on the `kaitai_struct_webide` repo, allowing it to trigger the workflow. (See more about token permissions on [this third-party action's readme](https://github.com/marketplace/actions/repository-dispatch#token).)

2024-08-16 09:49 UTC, generalmimon requested changes
@jtbandes Thanks for suggesting a possible solution. I don't see much value in using [`octokit/request-action`](https://github.com/octokit/request-action) though, it looks like a glorified "reimplementation" of `curl` in JavaScript. I'd rather use [`curl`](https://curl.se/) directly, which is a much more common dependency, comes preinstalled (so we don't have to worry about bumping its version once in a while), and is more flexible.

And I'd put the `curl` invocation to the [`trigger-kaitai_struct_webide`](https://github.com/kaitai-io/kaitai_struct/blob/a8afea8ef9f202bbd2687377e0921514d4fc451f/trigger-kaitai_struct_webide) script and call the script from the CI workflow config. You can replace its contents - it was only left for reference of how the trigger was done with Travis CI, but we don't use Travis anymore, so it's no longer used.

2024-08-16 19:48 UTC, jtbandes commented
Updated with curl command adapted from https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#create-a-repository-dispatch-event

2024-08-23 22:12 UTC, generalmimon approved these changes
@jtbandes Thanks! Let's try it in action.

2024-08-23 22:33 UTC, merged

2024-08-24 14:30 UTC, generalmimon commented
It looks like it should work now. I didn't get it right the first time (I should have done more local testing instead of just _assuming_ things), but https://github.com/kaitai-io/kaitai_struct_webide/actions/runs/10533243030 proves that the CI workflow of `kaitai_struct_webide` was successfully triggered from https://github.com/kaitai-io/kaitai_struct/actions/runs/10533223574/job/29188839941#step:6:10. Although the triggered CI run didn't actually update the compiler and runtime to latest versions (note that there is no update to either in https://github.com/kaitai-io/ide-kaitai-io.github.io/commit/dd70c744481031b216d906d0ca74792398c46b33), it appears that I finally fixed this in https://github.com/kaitai-io/kaitai_struct_webide/commit/2b6cfd5118a8563ab85abb4405e46082a5040b75 - see https://github.com/kaitai-io/ide-kaitai-io.github.io/commit/5fb4dacff403bcd79fd710ea34b7e2f488883996.

So now https://ide.kaitai.io/devel/ should be automatically kept up to date again.